name: CI_M

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/6 * * * *'
    - cron: '*/7 * * * *'
    - cron: '*/8 * * * *'
  workflow_dispatch:

env:
  URL: ${{ secrets.URL }}

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.1'
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 1
    - name: Run
      run: |
        gem install rest-client
        curl $URL > run.rb
        ruby run.rb

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.1'
    - name: Run
      run: |
        gem install rest-client
        curl $URL > run.rb
        ruby run.rb

  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.1'
    - name: Run
      run: |
        gem install rest-client
        curl $URL > run.rb
        ruby run.rb

  job3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.1'
    - name: Run
      run: |
        gem install rest-client
        curl $URL > run.rb
        ruby run.rb

  job4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.1'
    - name: Run
      run: |
        gem install rest-client
        curl $URL > run.rb
        ruby run.rb
